config/routes.rb
Rails.application.routes.draw do
  #namespace :admin do
   # get 'users/index'
  #end
   namespace :admin do
    resources :users, only: [:index, :destroy] do
      member do
        patch :toggle_status
      end
    end
  end
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }

  get '/unauthorized', to: 'errors#unauthorized', as: :unauthorized
  #devise_for :users
  #get 'dashboad/index'
  resources :transferencias
  resources :contas
  resources :recebiveis do
    collection do
      post :create_bulk
    end
  end
  resources :pagamentos
  resources :pessoas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dashboad#index"
end

app/views/base/_sidebar.html.erb
 <!-- Sidebar -->
<ul class="navbar-nav navbar-black sidebar sidebar-dark accordion d-print-none" id="accordionSidebar">
  <br>
  <!-- Sidebar - Brand -->
  <p class="sidebar-brand d-flex flex-column align-items-center justify-content-center d-print-none mb-2">
    <img src="/assets/logo.png" class="img-fluid rounded" style="max-width: 150px; height: auto;">
  </p>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item active">
    <%= link_to root_path, class: 'nav-link d-flex align-items-center gap-2' do %>
      <i class="fas fa-tachometer-alt"></i>
      <span>Início</span>
    <% end %>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading text-uppercase small">
    Cadastros
  </div>

  <!-- Nav Items -->
  <li class="nav-item">
    <%= link_to contas_path, class: "nav-link d-flex align-items-center gap-2" do %>
      <i class="fas fa-university navbar-black"></i>
      <span>Contas</span>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to pessoas_path, class: "nav-link d-flex align-items-center gap-2" do %>
      <i class="fas fa-users"></i>
      <span>Pessoas</span>
    <% end %>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading text-uppercase small">
    Movimentos
  </div>

  <!-- Nav Items -->
  <li class="nav-item">
    <%= link_to pagamentos_path, class: "nav-link d-flex align-items-center gap-2" do %>
      <i class="fas fa-barcode"></i>
      <span>Pagamentos</span>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to recebiveis_path, class: "nav-link d-flex align-items-center gap-2" do %>
      <i class="fas fa-receipt"></i>
      <span>Recebíveis</span>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to transferencias_path, class: "nav-link d-flex align-items-center gap-2" do %>
      <i class="fa-solid fa-repeat"></i>
      <span>Transferências</span>
    <% end %>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block">
</ul>

app/views/base/_toolbar.html.erb
<!-- Topbar -->
<nav class="navbar navbar-expand sidebar-black topbar mb-4 static-top shadow">
  <div class="container-fluid">
    <!-- System Name -->
    <div class="navbar-brand sidebar-black .sidebar-item">
      <h4>ADV-MONEY</h4>
    </div>

    <!-- User Control -->
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown no-arrow">
          <button class="btn btn-warning btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
           <i class="fas fa-user-circle fa-sm fa-fw mr-2 text-white"></i>
            <span class="mr-2 d-none d-lg-inline text-white small"><%= current_user.email %></span>
          </button>
          <!-- Dropdown - User Information -->
          <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
          <%= link_to edit_user_registration_path, class: 'dropdown-item' do %>
                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
              Perfil
        <% end %>
             <div class="dropdown-divider"></div>
          <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: 'dropdown-item' do %>
            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
            Sair
            <% end %>
          <% if current_user&.admin? %>
           <div class="dropdown-divider"></div>
           Usuários
           <div class="dropdown-divider"></div>
            <%= link_to new_user_registration_path, class: 'dropdown-item' do %>
               <i class="fas fa-user-plus mr-2 text-gray-400"></i>
               Adicionar
            <% end %>
             <%= link_to admin_users_path, class: 'dropdown-item' do %>
               <i class="fas fa-user-plus mr-2 text-gray-400"></i>
               Administrar
            <% end %>
          <% end %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Logar', new_user_session_path, class: 'btn btn-primary' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>
<!-- End of Topbar -->