config/routes.rb
Rails.application.routes.draw do
  #namespace :admin do
   # get 'users/index'
  #end
   namespace :admin do
    resources :users, only: [:index, :destroy] do
      member do
        patch :toggle_status
      end
    end
  end
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }

  get '/unauthorized', to: 'errors#unauthorized', as: :unauthorized
  #devise_for :users
  #get 'dashboad/index'
  resources :transferencias
  resources :contas
  resources :recebiveis do
    collection do
      post :create_bulk
    end
  end
  resources :pagamentos
  resources :pessoas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dashboad#index"
end

app/models/conta.rb
class Conta < ApplicationRecord
    has_many :recebiveis
    has_many :pagamentos
    has_many :transferencias_origem, class_name: 'Transferencia', foreign_key: 'saida'
    has_many :transferencias_destino, class_name: 'Transferencia', foreign_key: 'entrada'

    def saldo
        valor_inicial.to_d +
        recebiveis.sum(:valor_recebido) -
        pagamentos.sum(:valor) -
        transferencias_origem.sum(:valor_saida) +
        transferencias_destino.sum(:valor_saida)
    end

    def saldo_em(data)
        valor_inicial.to_d +
          recebiveis.where('data_pagamento <= ?', data).sum(:valor_recebido) -
          pagamentos.where('data_pagamento <= ?', data).sum(:valor) -
          transferencias_origem.where('data <= ?', data).sum(:valor_saida) +
          transferencias_destino.where('data <= ?', data).sum(:valor_saida)
      end
end

app/controllers/contas_controller.rb
class ContasController < ApplicationController
  before_action :set_conta, only: %i[ show edit update destroy ]
  before_action :authorize_admin
  # GET /contas or /contas.json
  def index
    @contas = Conta.all
  end

  # GET /contas/1 or /contas/1.json
  def show
    @conta = Conta.find(params[:id])
    @recebiveis = @conta.recebiveis.where(status: true).order(data_pagamento: :desc)
    @pagamentos = @conta.pagamentos.where(status: true).order(data_pagamento: :desc)
    @transferencias_origem = @conta.transferencias_origem.order(data: :desc)
    @transferencias_destino = @conta.transferencias_destino.order(data: :desc)

    @transacoes = (@recebiveis + @pagamentos + @transferencias_origem + @transferencias_destino).sort_by do |transacao|
      if transacao.is_a?(Recebivel) || transacao.is_a?(Pagamento)
        transacao.data_pagamento || Time.at(0)
      elsif transacao.is_a?(Transferencia)
        transacao.data || Time.at(0)
      end
    end
  end

  # GET /contas/new
  def new
    @conta = Conta.new
  end

  # GET /contas/1/edit
  def edit
  end

  # POST /contas or /contas.json
  def create
    @conta = Conta.new(conta_params)

    respond_to do |format|
      if @conta.save
        format.html { redirect_to conta_url(@conta), notice: "Conta was successfully created." }
        format.json { render :show, status: :created, location: @conta }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @conta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contas/1 or /contas/1.json
  def update
    respond_to do |format|
      if @conta.update(conta_params)
        format.html { redirect_to conta_url(@conta), notice: "Conta was successfully updated." }
        format.json { render :show, status: :ok, location: @conta }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @conta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contas/1 or /contas/1.json
  def destroy
    @conta.destroy!

    respond_to do |format|
      format.html { redirect_to contas_url, notice: "Conta was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conta
      @conta = Conta.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def conta_params
      params.require(:conta).permit(:descricao, :valor_inicial, :cor_fundo, :cor_fonte)
    end
end

app/helpers/contas_helper.rb
module ContasHelper
end

app/views/contas/_conta.html.erb
<div id="<%= dom_id conta %>">

</div>

app/views/contas/_form.html.erb
<%= form_with(model: conta, local: true, class: "mt-4") do |form| %>
  <% if conta.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(conta.errors.count, "erro") %> impediram o salvamento desta conta:</h4>
      <ul>
        <% conta.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :descricao, class: "form-label" %>
    <%= form.text_field :descricao, class: "form-control", placeholder: "Digite a descrição da conta" %>
  </div>

  <div class="form-group">
    <%= form.label :valor_inicial, class: "form-label" %>
    <%= form.text_field :valor_inicial, class: "form-control col-md-3", placeholder: "Digite o valor inicial" %>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label :cor_fundo, "Cor de Fundo", class: "form-label" %>
      <%= form.color_field :cor_fundo, class: 'form-control' %>
    </div>
    
    <div class="form-group col-md-6">
      <%= form.label :cor_fonte, "Cor da Fonte", class: "form-label" %>
      <%= form.color_field :cor_fonte, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group mt-3">
    <%= form.submit "Salvar Conta", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/contas/edit.html.erb
<h1>Editar Conta</h1>

<%= render "form", conta: @conta %>

<br>

<div>
  <%= link_to "Conta", @conta %> |
  <%= link_to "Voltar", contas_path %>
</div>

app/views/contas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Contas</h1>

<div class="container mt-5">
  <div class="row">
    <% @contas.each do |conta| %>
      <div class="col-md-4 mb-3">
        <div class="card shadow-sm" style="background-color: #f8f9fa;">
          <div class="card-body">
            <h5 class="card-title text-primary font-weight-bold"><%= conta.descricao %></h5>
            <p class="card-text mb-2">
              <strong>Valor Inicial:</strong> <%= number_to_currency(conta.valor_inicial) %>
            </p>
            <p class="card-text mb-1">
              <strong>Saldo Atual:</strong> 
              <h4 class="my-1 text-info"><%= number_to_currency(conta.saldo) %></h4> 
            </p>
          </div>
          <div class="card-footer d-flex justify-content-between bg-white border-top-0">
            <%= link_to 'Ver Detalhes', conta_path(conta), class: 'btn btn-outline-primary btn-sm' %>
            <%= link_to 'Editar', edit_conta_path(conta), class: 'btn btn-outline-secondary btn-sm' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= link_to "Adicionar Conta", new_conta_path %>

app/views/contas/new.html.erb
<h1>Adicionar Conta</h1>

<%= render "form", conta: @conta %>

<br>

<div>
  <%= link_to "Voltar", contas_path %>
</div>

app/views/contas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @conta %>
<div class="container mt-5">
  <h2>Extrato da Conta: <%= @conta.descricao %></h2>
  <p>
    <strong>Valor inicial:</strong>
    <%= format_curr(@conta.valor_inicial) %>
  </p>
  <p>Saldo Atual: <h2 class="font-weight-bold"><%= number_to_currency(@conta.saldo) %></h2></p>

  <h3>Extrato</h3>
  <table class="table table-bordered table-hover mt-3">
    <thead>
      <tr>
        <th>Data</th>
        <th>Descrição</th>
        <th>Tipo</th>
        <th>Valor</th>
        <th class="d-print-none">Ação</th>
      </tr>
    </thead>
    <tbody>
      <% @transacoes.reverse.each do |transacao| %>
        <% if transacao.is_a?(Recebivel) %>
          <tr class="table-success">
            <td><%= format_date(transacao.data_pagamento) %></td>
            <td>Recebível </td>
            <td>Entrada</td>
            <td><%= number_to_currency(transacao.valor_recebido) %></td>
            <td class="d-print-none"> <%= link_to recebivel_path(transacao.id), class: "btn btn-info btn-sm d-print-none" do %>
             <i class="fas fa-eye fa-sm text-black"></i>         
             <% end %>
           </td>
          </tr>
        <% elsif transacao.is_a?(Pagamento) %>
          <tr class="table-danger">
            <td><%= format_date(transacao.data_pagamento) %></td>
            <td>Pagamento</td>
            <td>Saída</td>
            <td><%= number_to_currency(transacao.valor) %></td>
             <td class="d-print-none"> <%= link_to pagamento_path(transacao.id), class: "btn btn-info btn-sm d-print-none" do %>
             <i class="fas fa-eye fa-sm text-black"></i>         
             <% end %>
           </td>
          </tr>
        <% elsif transacao.is_a?(Transferencia) && transacao.saida == @conta.id %>
          <tr class="table-warning">
            <td><%= format_date(transacao.data) %></td>
            <td>Transferência para <%= Conta.find(transacao.entrada).descricao %></td>
            <td>Saída</td>
            <td><%= number_to_currency(transacao.valor_saida) %></td>
             <td class="d-print-none"> <%= link_to transferencia_path(transacao.id), class: "btn btn-info btn-sm d-print-none" do %>
             <i class="fas fa-eye fa-sm text-black"></i>         
             <% end %>
           </td>
          </tr>
        <% elsif transacao.is_a?(Transferencia) && transacao.entrada == @conta.id %>
          <tr class="table-info">
            <td><%= format_date(transacao.data) %></td>
            <td>Transferência de <%= Conta.find(transacao.saida).descricao %></td>
            <td>Entrada</td>
            <td><%= number_to_currency(transacao.valor_saida) %></td>
            <td class="d-print-none"> <%= link_to transferencia_path(transacao.id), class: "btn btn-info btn-sm d-print-none" do %>
             <i class="fas fa-eye fa-sm text-black"></i>         
             <% end %>
           </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>