config/routes.rb
Rails.application.routes.draw do
  #namespace :admin do
   # get 'users/index'
  #end
   namespace :admin do
    resources :users, only: [:index, :destroy] do
      member do
        patch :toggle_status
      end
    end
  end
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }

  get '/unauthorized', to: 'errors#unauthorized', as: :unauthorized
  #devise_for :users
  #get 'dashboad/index'
  resources :transferencias
  resources :contas
  resources :recebiveis do
    collection do
      post :create_bulk
    end
  end
  resources :pagamentos
  resources :pessoas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dashboad#index"
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
    has_many :pagamentos
    has_many :recebiveis
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  before_action :set_pessoa, only: %i[ show edit update destroy ]

  # GET /pessoas or /pessoas.json
  def index
    @pessoas = Pessoa.all

    # Filtragem
    @pessoas = @pessoas.where("nome ILIKE ?", "%#{params[:nome]}%") if params[:nome].present?
    @pessoas = @pessoas.where("cidade ILIKE ?", "%#{params[:cidade]}%") if params[:cidade].present?

    # Ordenação
    @pessoas = @pessoas.order(params[:sort] => params[:direction]) if params[:sort].present? && params[:direction].present?

      # Paginação
    @pessoas = @pessoas.page(params[:page]).per(10)
  end

  # GET /pessoas/1 or /pessoas/1.json
  def show
  end

  # GET /pessoas/new
  def new
    @pessoa = Pessoa.new
  end

  # GET /pessoas/1/edit
  def edit
  end

  # POST /pessoas or /pessoas.json
  def create
    @pessoa = Pessoa.new(pessoa_params)

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to pessoa_url(@pessoa), notice: "Pessoa was successfully created." }
        format.json { render :show, status: :created, location: @pessoa }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pessoas/1 or /pessoas/1.json
  def update
    respond_to do |format|
      if @pessoa.update(pessoa_params)
        format.html { redirect_to pessoa_url(@pessoa), notice: "Pessoa was successfully updated." }
        format.json { render :show, status: :ok, location: @pessoa }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1 or /pessoas/1.json
  def destroy
    @pessoa.destroy!

    respond_to do |format|
      format.html { redirect_to pessoas_url, notice: "Pessoa was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa
      @pessoa = Pessoa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pessoa_params
      params.require(:pessoa).permit(:nome, :endereco, :bairro, :cidade, :email, :telefone)
    end
end

app/helpers/pessoas_helper.rb
module PessoasHelper
    def sortable(column, title = nil)
        title ||= column.titleize
        direction = (column == params[:sort] && params[:direction] == "asc") ? "desc" : "asc"
        link_to title, sort: column, direction: direction, nome: params[:nome], cidade: params[:cidade]
    end
end

app/views/pessoas/_form.html.erb
<%= form_with(model: pessoa, local: true, class: "needs-validation") do |form| %>
  <% if pessoa.errors.any? %>
    <div class="alert alert-danger">
      <h4 class="alert-heading"><%= pluralize(pessoa.errors.count, "erros") %> impediram este pessoa de ser salvo:</h4>
      <ul>
        <% pessoa.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :nome, class: "form-label" %>
    <%= form.text_field :nome, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :endereco, class: "form-label" %>
    <%= form.text_field :endereco, class: "form-control", required: true %>
  </div>
<div class= "row">
  <div class="col mb-3">
    <%= form.label :bairro, class: "form-label" %>
    <%= form.text_field :bairro, class: "form-control", required: true %>
  </div>

  <div class="col mb-3">
    <%= form.label :cidade, class: "form-label" %>
    <%= form.text_field :cidade, class: "form-control", required: true %>
  </div>
</div>
 <div class= "row">
  <div class="col mb-3">
    <%= form.label :email, class: "form-label" %>
    <%= form.email_field :email, class: "form-control", required: true %>
  </div>

  <div class="col mb-3">
    <%= form.label :telefone, class: "form-label" %>
    <%= form.telephone_field :telefone, class: "form-control", required: true %>
  </div>
</div>
<div class="row">
  <div class="mb-3">
    <%= form.submit "Salvar", class: "btn btn-primary" %>
  </div>
  <div class="mb-3">
    <%= link_to "Voltar", pessoas_path, class:"btn btn-secondary"  %>
 </div>
 </div>
<% end %>
 

app/views/pessoas/_pessoa.html.erb
<div id="<%= dom_id pessoa %>">
  <p>
    <strong>Nome:</strong>
    <%= pessoa.nome %>
  </p>

  <p>
    <strong>Endereco:</strong>
    <%= pessoa.endereco %>
  </p>

  <p>
    <strong>Bairro:</strong>
    <%= pessoa.bairro %>
  </p>

  <p>
    <strong>Cidade:</strong>
    <%= pessoa.cidade %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= pessoa.email %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= pessoa.telefone %>
  </p>

</div>

app/views/pessoas/edit.html.erb
<h1>Editando pessoa</h1>

<%= render "form", pessoa: @pessoa %>

<br>

app/views/pessoas/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <h1>Pessoas</h1>

<div class="d-sm-flex align-items-center justify-content-between mb-6">
   <!-- Button to trigger modal -->
  <button type="button" class="d-none d-sm-inline-block btn btn-sm btn-warning shadow-sm d-print-none" data-bs-toggle="modal" data-bs-target="#newPessoaModal">
    <i class="fas fa-download fa-sm text-white-50"></i>
    Adicionar
  </button>
 
    <button type="button" class="d-none d-sm-inline-block btn btn-sm btn-secondary shadow-sm d-print-none" data-bs-toggle="modal" data-bs-target="#filterModal">
      <i class="fas fa-filter fa-sm text-white-50"></i>
      Filtros
    </button>  
 
 </div>


<div class="modal fade" id="filterModal" tabindex="-1" aria-labelledby="filterModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="filterModalLabel">Filtrar Resultados</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form class="row g-3 mb-4" method="get">
          <div class="col-auto">
            <input type="text" class="form-control" name="nome" placeholder="Nome" value="<%= params[:nome] %>">
          </div>
          <div class="col-auto">
            <input type="text" class="form-control" name="cidade" placeholder="Cidade" value="<%= params[:cidade] %>">
          </div>
          <div class="col-auto">
            <button type="submit" class="btn btn-primary mb-3">Filtrar</button>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

 <!-- Botão para abrir o modal -->
  <!-- Tabela -->
  <% if @pessoas.count > 0 %>

<p></p>
  <table class="table table-striped table-sm table-hover">
    <thead>
      <tr>
        <th><%= sortable "nome", "Nome" %></th>
        <th><%= sortable "cidade", "Cidade" %></th>
        <th>Email</th>
        <th>Telefone</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      <% @pessoas.each do |pessoa| %>
        <tr>
          <td><%= pessoa.nome %></td>
          <td><%= pessoa.cidade %></td>
          <td><%= pessoa.email %></td>
          <td><%= pessoa.telefone %></td>
          <td>
          <%= link_to pessoa, class: "btn btn-info btn-sm d-print-none" do %>
          <i class="fas fa-eye fa-sm text-black"></i>         
          <% end %>
          <%= link_to edit_pessoa_path(pessoa), class: "btn btn-warning btn-sm d-print-none" do %>
            <i class="fas fa-pencil fa-sm text-black"></i>
          <% end %>    
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <!-- Links de Paginação -->
  <div class="fixed-bottom d-flex justify-content-center align-items-center d-print-none">
     <%= paginate @pessoas %>
  </div>  
  <% else %>
    <h5> Nenhuma Pessoa encontrada </h5>
  <% end %> 
</div>

<!-- Modal -->
<div class="modal fade" id="newPessoaModal" tabindex="-1" aria-labelledby="newPessoaModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newPessoaModalLabel">Inserir Nova Pessoa</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with model: Pessoa.new, url: pessoas_path, local: true do |form| %>
          <div class="mb-3">
            <%= form.label :nome, class: "form-label " %>
            <%= form.text_field :nome, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= form.label :endereco, class: "form-label" %>
            <%= form.text_field :endereco, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= form.label :bairro, class: "form-label"  %>
            <%= form.text_field :bairro, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= form.label :cidade, class: "form-label " %>
            <%= form.text_field :cidade, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= form.label :email, class: "form-label" %>
            <%= form.email_field :email, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= form.label :telefone, class: "form-label" %>
            <%= form.text_field :telefone, class: "form-control" %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
            <%= form.submit "Salvar", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pessoas/new.html.erb
<h1>Inserir pessoa</h1>

<%= render "form", pessoa: @pessoa %>

<br>

app/views/pessoas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pessoa %>

<div>
  <%= link_to "Editar", edit_pessoa_path(@pessoa), class: "btn btn-sm btn-warning" %> 
  <%= link_to "Voltar", pessoas_path, class: "btn btn-sm btn-secondary" %>
  
<!-- Button trigger modal -->
<button type="button" class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
  Apagar
</button>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">Deseja realmente apagar o registo? </h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <ul class="list-group">
        <li class="list-group-item">Data: <%= format_date(@pessoa.created_at) %></li>
        <li class="list-group-item">Pessoa: <%= @pessoa.nome %></li>
        <li class="list-group-item">Cidade: <%= @pessoa.cidade %></li>
       </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
         <%= button_to "Delete", @pessoa, method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>
</div>