config/routes.rb
Rails.application.routes.draw do
  #namespace :admin do
   # get 'users/index'
  #end
   namespace :admin do
    resources :users, only: [:index, :destroy] do
      member do
        patch :toggle_status
      end
    end
  end
  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
  }

  get '/unauthorized', to: 'errors#unauthorized', as: :unauthorized
  #devise_for :users
  #get 'dashboad/index'
  resources :transferencias
  resources :contas
  resources :recebiveis do
    collection do
      post :create_bulk
    end
  end
  resources :pagamentos
  resources :pessoas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dashboad#index"
end

app/models/pagamento.rb
class Pagamento < ApplicationRecord
  belongs_to :pessoa
 # enum status: [:Pendente, :Pago]
  before_save :convert_comma_to_dot

  scope :pagos, -> { where(status: true) }
  scope :a_pagar, -> { where(status: false).or(where(status: nil)).where('vencimento >= ?', Date.today) }
  scope :vencidos, -> { where(status: false).or(where(status: nil)).where('vencimento < ?', Date.today) }
  scope :pagar_hoje, -> { where(status: false).or(where(status: nil)).where('vencimento = ?', Date.today) }
  private

  def convert_comma_to_dot
    self.valor_pago = valor_pago.to_s.gsub(',', '.').to_f if valor_pago.present?
    self.valor = valor.to_s.gsub(',', '.').to_f if valor.present?
  end
end

app/controllers/pagamentos_controller.rb
class PagamentosController < ApplicationController
  before_action :set_pagamento, only: %i[ show edit update destroy ]

  # GET /pagamentos or /pagamentos.json
  def index
    column = params[:column]
    direction = params[:direction]
    @pagamentos = Pagamento.joins(:pessoa)
    
    @items_per_page = params[:items_per_page] || 10

    if params[:pessoa_id].present?
      @pagamentos = @pagamentos.where(pessoa_id: params[:pessoa_id])
    end

    if params[:status].present?
      @pagamentos = @pagamentos.where(status: params[:status])
    end

    if params[:categoria].present?
      @pagamentos = @pagamentos.where(categoria: params[:categoria])
    end

    if params[:entrada_inicio].present? && params[:entrada_fim].present?
      entrada_fim = params[:entrada_fim]
      # Converta a string para um objeto Date
      entrada_fim = Date.parse(entrada_fim) if entrada_fim.present?
      # Converta para o final do dia
      entrada_fim = entrada_fim.end_of_day if entrada_fim      
      @pagamentos = @pagamentos.where(created_at: params[:entrada_inicio]..entrada_fim)
    end
    if params[:vencimento_inicio].present? && params[:vencimento_fim].present?
      @pagamentos = @pagamentos.where(vencimento: params[:vencimento_inicio]..params[:vencimento_fim])
    end
    if params[:pagamento_inicio].present? && params[:pagamento_fim].present?
      @pagamentos = @pagamentos.where(data_pagamento: params[:pagamento_inicio]..params[:pagamento_fim])
    end

    if column.present? && direction.present?
      if column == 'pessoa_name'
        @pagamentos = @pagamentos.order("pessoas.nome #{direction}")
      else
        @pagamentos = @pagamentos.order("#{column} #{direction}")
      end
    end
    
    @pagamentos = case params[:filter]
      when 'pagos'
        @pagamentos.pagos
      when 'a_pagar'
        @pagamentos.a_pagar
      when 'vencidos'
        @pagamentos.vencidos
      when 'pagar_hoje'
        @pagamentos.pagar_hoje 
      else
        @pagamentos.all.order(id: :desc)
      end
   
    @pagamentosf = @pagamentos
    @pagamentos = @pagamentos.page(params[:page]).per(@items_per_page)

  end

  # GET /pagamentos/1 or /pagamentos/1.json
  def show
    
  end

  # GET /pagamentos/new
  def new
    @pagamento = Pagamento.new
  end

  # GET /pagamentos/1/edit
  def edit
  end

  # POST /pagamentos or /pagamentos.json
  def create
    @pagamento = Pagamento.new(pagamento_params)

    respond_to do |format|
      if @pagamento.save
        format.html { redirect_to pagamento_url(@pagamento), notice: "Pagamento Criado com Sucesso!." }
        format.json { render :show, status: :created, location: @pagamento }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pagamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pagamentos/1 or /pagamentos/1.json
  def update
    respond_to do |format|
      if @pagamento.update(pagamento_params)
        format.html { redirect_to pagamento_url(@pagamento), notice: "Pagamento Atualizado com Sucesso!" }
        format.json { render :show, status: :ok, location: @pagamento }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pagamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pagamentos/1 or /pagamentos/1.json
  def destroy
    @pagamento.destroy!

    respond_to do |format|
      format.html { redirect_to pagamentos_url, notice: "Pagamento DELETADO com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pagamento
      @pagamento = Pagamento.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pagamento_params
      params.require(:pagamento).permit(:pessoa_id, :vencimento, :valor, :data_pagamento, :status, :valor_pago, :conta_id, :categoria, :descricao)
    end
end

app/helpers/pagamentos_helper.rb
module PagamentosHelper
      def sort_link(column:, label:)
        # Mescla os parâmetros de filtro atuais com os parâmetros de ordenação
        link_params = request.query_parameters.merge({ column: column, direction: next_direction(column) })
      
        # Gera o link com os parâmetros mesclados
        link_to(label, pagamentos_path(link_params))
      end
      
      def next_direction(column)
        if column == params[:column]
          params[:direction] == 'asc' ? 'desc' : 'asc'
        else
          'asc'
        end
      end

      def items_per_page_form(current_params)
        form_with(url: pagamentos_path, method: :get, local: true) do |form|
          current_params.each do |key, value|
            concat form.hidden_field key, value: value unless key == 'items_per_page'
          end
          concat form.label :items_per_page, 'Itens por página:'
          concat form.select :items_per_page, options_for_select([10, 20, 30, 50, 100, Pagamento.count], current_params[:items_per_page].to_i), {}, onchange: 'this.form.submit();'
        end
      end
      
end

app/views/pagamentos/_form.html.erb
        <%= form_with(model: @pagamento) do |form| %>
          <div class="row">
            <div class="col-md-6">
              <div class="mb-3">
                <%= form.label :pessoa_id, style: "display: block" %>
                 <%= form.select :pessoa_id, 
                options_from_collection_for_select(Pessoa.all.order(:nome), :id, :nome, @pagamento.pessoa_id), 
                { include_blank: true }, 
                { class: "form-select" } %>
              </div>

              <div class= "row">
                  <div class="col mb-3">
                    <%= form.label :vencimento, style: "display: block" %>
                    <%= form.date_field :vencimento, class: "form-control" %>
                  </div>
                  <div class="col mb-3">
                    <%= form.label :valor, style: "display: block" %> 
                    <%= form.text_field :valor, class: "form-control", id:"valor",type: "number", step: "0.01", min: "0.01" %>
                  </div>
              </div>
            
              <div class= "row">
                    <div class="form-group col mb-3">
                        <%= form.label :categoria %>
                        <%= form.text_field :categoria, class: 'form-control' %>
                    </div>
              </div>
              <div class="row"> 
              <div class="form-group col mb-3">
                    <%= form.label :descricao %>
                    <%= form.text_area :descricao, class: 'form-control' %>
              </div>
              </div>
            </div>



            <div class="col-md-6">
             <div class="p-3 mb-3 border border-primary rounded text-black">
              <div class="mb-3">
                <%= form.label :data_pagamento, style: "display: block" %>
                <%= form.date_field :data_pagamento, class: "form-control" %>
              </div>
             
              <div class="mb-3">
              <%= form.label :conta_id, style: "display: block" %>
              <%= form.select :conta_id, 
                options_from_collection_for_select(Conta.all.order(:descricao), :id, :descricao, @pagamento.conta_id), 
                { include_blank: true }, 
                { class: "form-select" } %>
              </div>            
              
              <div class= "row">
              <div class= "col">
              <div class="mb-2">
                <%= form.label :valor_pago, style: "display: block" %>
                <%= form.text_field :valor_pago, class: "form-control", id: "valor_pago", type: "number", step: "0.01", min: "0.01" %>
              </div>
              </div>
              <div class= "col"> 
              <div class="mb-2">
                <%= form.label :status, style: "display: block" %>
                <%= form.select :status,
                options_for_select([['Pago', 1], ['Pendente', 0]], @pagamento.status),
                { include_blank: true },
                { class: "form-select" } %>
                </div>
              </div>
              </div>

            </div>
            </div>
          </div>

          <div class="modal-footer">
            <%= form.submit 'Salvar', class: "btn btn-primary" %>
            <%= link_to "Cancelar", pagamentos_path, class: "btn btn-secondary" %>
          </div>
        <% end %>

app/views/pagamentos/_pagamento.html.erb
<div id="<%= dom_id pagamento %>">
  <p>
    <strong>Pessoa:</strong>
    <%= pagamento.pessoa.nome %>
  </p>

  <p>
    <strong>Categória:</strong>
    <%= pagamento.categoria %>
  </p>

  <p>
    <strong>descricao:</strong>
    <%= pagamento.descricao %>
  </p>


  <p>
    <strong>Vencimento:</strong>
    <%= format_date(pagamento.vencimento) %>
  </p>

  <p>
    <strong>Valor:</strong>
    <%= format_curr(pagamento.valor) %>
  </p>

  <p>
    <strong>Data pagamento:</strong>
    <%= format_date(pagamento.data_pagamento) %>
  </p>

  
  <p>
    <strong>Status:</strong>
    <%= pagamento.status == 1 ? "Pago" : "Pendente" %>
  </p>

  <p>
    <strong>Valor pago:</strong>
    <%= format_curr(pagamento.valor_pago) %>
  </p>

</div>

app/views/pagamentos/edit.html.erb
<h1>Editando Pagamento</h1>

<%= render "form", pagamento: @pagamento %>

app/views/pagamentos/index.html.erb
 <div class="d-sm-flex align-items-center justify-content-between mb-6">
    <h1 class="h3 mb-0 text-gray-800">Pagamentos </h1><p class="fst-italic d-print-none"><%= Pagamento.count == @pagamentosf.count ? "Registro(s): #{Pagamento.count}" : "Filtrado: #{@pagamentosf.count} de #{Pagamento.count}" %></p>
 </div>
 <div class="d-sm-flex align-items-center justify-content-between mb-6">
   <!-- Button to trigger modal -->
   
    <%= link_to new_pagamento_path, class: "d-none d-sm-inline-block btn btn-sm btn-warning shadow-sm d-print-none" do %>
          <i class="fas fa-download fa-sm text-white-50"></i>
          Adicionar
    <% end %>

    <div class="btn-group btn-group-sm mb-3 d-print-none" role="group" aria-label="Filtros de Pagamento">
      <%= link_to 'Todos', url_for(params.permit!.to_h.except(:filter)), class: "btn btn-outline-primary #{'active' unless params[:filter].present?}" %>
      <%= link_to 'Pagos', url_for(params.permit!.to_h.merge(filter: 'pagos')), class: "btn btn-outline-primary #{'active' if params[:filter] == 'pagos'}" %>
      <%= link_to 'A Pagar', url_for(params.permit!.to_h.merge(filter: 'a_pagar')), class: "btn btn-outline-primary #{'active' if params[:filter] == 'a_pagar'}" %>
      <%= link_to 'Vencidos', url_for(params.permit!.to_h.merge(filter: 'vencidos')), class: "btn btn-outline-primary #{'active' if params[:filter] == 'vencidos'}" %>
      <%= link_to 'Hoje', url_for(params.permit!.to_h.merge(filter: 'pagar_hoje')), class: "btn btn-outline-primary #{'active' if params[:filter] == 'pagar_hoje'}" %>
    </div>

 
    <button type="button" class="d-none d-sm-inline-block btn btn-sm btn-secondary shadow-sm d-print-none" data-bs-toggle="modal" data-bs-target="#filtroModal">
      <i class="fas fa-filter fa-sm text-white-50"></i>
      Abrir Filtro
    </button>  
  
 </div>

<div class="modal fade" id="filtroModal" tabindex="-1" aria-labelledby="filtroModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="filtroModalLabel">Filtrar Pagamentos</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with url: pagamentos_path, method: :get, local: true, class: "row g-3" do %>
          <div class="row">
            <div class="col-md-5">
              <%= label_tag :pessoa_id, "Pessoa", class: "form-label" %>
              <%= select_tag :pessoa_id, options_from_collection_for_select(Pessoa.all.order(:nome), :id, :nome, params[:pessoa_id]), include_blank: true, class: "form-select" %>
            </div>
            <div class="col-md-3">
              <%= label_tag :status, "Status", class: "form-label" %>
              <%= select_tag :status, options_for_select([['Pago', 1], ['Pendente', 0]], params[:status]), include_blank: true, class: "form-select" %>
            </div>
              <div class="col-md-3">
              <%= label_tag :categoria, "Categória", class: "form-label" %>
              <%= text_field_tag :categoria, params[:categoria], class: "form-control" %>
            </div>
          </div>

          <div class="row mt-3">
            <div class="col-md-4">
              <div class="card">
                <h5 class="card-header">Período Entrada</h5>
                <div class="card-body">
                  <div class="col">
                    <%= label_tag :entrada_inicio, "Início", class: "form-label" %>
                    <%= date_field_tag :entrada_inicio, params[:entrada_inicio], class: "form-control" %>
                    <%= label_tag :entrada_fim, "Final", class: "form-label mt-2" %>
                    <%= date_field_tag :entrada_fim, params[:entrada_fim], class: "form-control" %>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-md-4">
              <div class="card">
                <h5 class="card-header">Período Vencimento</h5>
                <div class="card-body">
                  <div class="col">
                    <%= label_tag :vencimento_inicio, "Início", class: "form-label" %>
                    <%= date_field_tag :vencimento_inicio, params[:vencimento_inicio], class: "form-control" %>
                    <%= label_tag :vencimento_fim, "Final", class: "form-label mt-2" %>
                    <%= date_field_tag :vencimento_fim, params[:vencimento_fim], class: "form-control" %>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-md-4">
              <div class="card">
                <h5 class="card-header">Período Pagamento</h5>
                <div class="card-body">
                  <div class="col">
                    <%= label_tag :pagamento_inicio, "Início", class: "form-label" %>
                    <%= date_field_tag :pagamento_inicio, params[:pagamento_inicio], class: "form-control" %>
                    <%= label_tag :pagamento_fim, "Final", class: "form-label mt-2" %>
                    <%= date_field_tag :pagamento_fim, params[:pagamento_fim], class: "form-control" %>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="row mt-4">
            <div class="col d-flex justify-content-center">
              <%= submit_tag "Filtrar", class: "btn btn-primary w-25" %>
            </div>
          </div>
        
        <% end %>
      </div>
    </div>
  </div>
</div>


<p style="color: green"><%= notice %></p>

<div class="container">
  
 <div class="table-responsive-sm">
  <table class="table table-sm table-hover table-striped mt-2 text-muted">
    <thead>
      <tr>
        <th class="text-center"><%= sort_link(column: "created_at", label: "Entrada") %></th>
        <th><%= sort_link(column: "pessoa_name", label: "Fornecedor") %> </th>
        <th> <%= sort_link(column: "categoria", label: "Categória") %></th>
        <th> <%= sort_link(column: "descricao", label: "Descrição") %></th>
        <th class="text-center"><%= sort_link(column: "vencimento", label: "Vencimento") %></th>
        <th class="text-center"><%= sort_link(column: "valor", label: "Valor") %></th>
        <th class="text-center"><%= sort_link(column: "data_pagamento", label: "Pago") %></th>
        <th class="text-center"><%= sort_link(column: "status", label: "Status") %></th>
        <th class="text-center d-print-none">Ações</th>
      </tr>
    </thead>
    <tbody>
      <% valor_por_pagina = 0 %>
      <% @pagamentos.each do |pagamento| %>
       <% if pagamento.vencimento.present? %> 
       <% vencido_e_nao_pago = pagamento.vencimento < Date.today && pagamento.status != 1 %>
       <tr <%= "class=table-danger" if vencido_e_nao_pago %>>
       <% else %>
       <tr>
       <% end %>
          <td class="text-center"><%= format_date(pagamento.created_at, :default ) %></td>
          <td><%= pagamento.pessoa.nome %></td>
          <td><%= pagamento.categoria %></td>          
          <td class="small text-truncate" style="max-width: 250px;"> <%=pagamento.descricao %></td>         
          <td class="text-center"><%= format_date(pagamento.vencimento) %></td>
          <td class="text-end"><%= format_curr(pagamento.valor) %></td>
          <td class="text-center"><%= format_date(pagamento.data_pagamento) %></td>
          <td class="text-center"><%= pagamento.status == 1 ? '<i class="fas fa-check fa-sm text-success"></i>'.html_safe : '<i class="fas fa-times fa-sm text-danger"></i>'.html_safe %></td>
          <td class="text-end d-print-none">
          <%= link_to pagamento, class: "btn btn-info btn-sm d-print-none" do %>
          <i class="fas fa-eye fa-sm text-black"></i>         
          <% end %>
          <%= link_to edit_pagamento_path(pagamento), class: "btn btn-warning btn-sm d-print-none" do %>
          <i class="fas fa-pencil fa-sm text-black"></i>
           <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
 <td>

<div class= "d-print-none">
  <%= items_per_page_form(request.query_parameters) %>
</div>

 </td>
      <td ></td>
      <td ></td>
      <td ></td>
      <td class="text-center">Total</td>
      <td class="text-end fw-bold"><%= format_curr(@pagamentosf.sum(:valor)) %></td>
  
</table>
</div>
      <div class="fixed-bottom d-flex justify-content-center align-items-center d-print-none">
         <%= paginate @pagamentos %>
      </div> 
</div>

<script>
document.addEventListener("DOMContentLoaded", function() {
  var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
  var tooltipList = tooltipTriggerList.map(function(tooltipTriggerEl) {
    return new bootstrap.Tooltip(tooltipTriggerEl);
  });
});
</script>

app/views/pagamentos/new.html.erb
<h1>Novo pagamento</h1>

<%= render "form", pagamento: @pagamento %>

app/views/pagamentos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pagamento %>

<div>
  <%= link_to "Editar", edit_pagamento_path(@pagamento), class: "btn btn-sm btn-primary" %>
  <%= link_to "Voltar", pagamentos_path, class: "btn btn-sm btn-secondary"%>
<!-- Button trigger modal -->
<button type="button" class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
  Apagar
</button>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">Deseja realmente apagar o registo? </h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <ul class="list-group">
        <li class="list-group-item">Data: <%= format_date(@pagamento.created_at) %></li>
        <li class="list-group-item">Pessoa: <%= Pessoa.find(@pagamento.pessoa_id).nome %></li>
        <li class="list-group-item">Valor: <%= @pagamento.valor %></li>
        <li class="list-group-item">Vencimento <%= format_date(@pagamento.vencimento) %></li>
      </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
         <%= button_to "Delete", @pagamento, method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

</div>